package eu.seatter.homeheating.edge.controller;

import eu.seatter.homeheating.edge.commands.RegistrationCommand;
import eu.seatter.homeheating.edge.converters.DeviceCommandToDevice;
import eu.seatter.homeheating.edge.converters.DeviceToRegistrationCommand;
import eu.seatter.homeheating.edge.model.Device;
import eu.seatter.homeheating.edge.service.DeviceService;
import eu.seatter.homeheating.edge.service.RegistrationService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

/**
 * Created by IntelliJ IDEA.
 * User: jas
 * Date: 25/01/2019
 * Time: 11:18
 */
@Slf4j
@RestController
@RequestMapping(value = "/api/v1/registration")
public class RegistrationController {
    private final RegistrationService registrationService;

    private final DeviceCommandToDevice convertDeviceCommandToDevice;
    private final DeviceToRegistrationCommand convertDeviceToRegistrationCommand;

    public RegistrationController(RegistrationService registrationService, DeviceService deviceService, DeviceCommandToDevice convertDeviceCommandToDevice, DeviceToRegistrationCommand convertDeviceToRegistrationCommand) {
        this.registrationService = registrationService;
        this.convertDeviceCommandToDevice = convertDeviceCommandToDevice;
        this.convertDeviceToRegistrationCommand = convertDeviceToRegistrationCommand;
    }

    /**
     * Register a new Collector device.
     *
     * @param registrationCommand A JSON formatted RegistrationCommand in the Request Body
     * @return A JSON formatted RegistrationCommand object
     */
    @PostMapping(value = {"device/new","device/new"}, consumes = "application/json;charset=UTF-8")
    @ResponseStatus(HttpStatus.CREATED)
    public RegistrationCommand newDevice(@Validated @RequestBody RegistrationCommand registrationCommand) {
        Device device = registrationService.newDevice(registrationCommand).orElseGet(Device::new);
        return convertDeviceToRegistrationCommand.convert(device);
    }


    /**
     * Get a Collector devices registration information
     *
     * @param uniqueId The uniqueID of the Collector device which is an encoded value generated by the Collector device itself
     * @return A JSON formatted RegistrationCommand object
     */
//    @GetMapping(value = {"device/{encodedID}"})
//    public RegistrationCommand getDeviceRegistration(@PathVariable String encodedID) {
        @GetMapping(value = {"device"})
        public RegistrationCommand getDeviceRegistration(@RequestParam("uniqueId") String uniqueId) {
        log.debug("Requested device registration information: unique ID : " + uniqueId);
        Device device = registrationService.getRegistration(uniqueId).orElseGet(Device::new);
        return convertDeviceToRegistrationCommand.convert(device);
    }


}
